### ISSUE TITLE
DroneVehicle数据集标签问题

### ISSUE THREAD

**Issue by Another-0** [hexiao-cs/CALNet-Dronevehicle#1]
我想知道论文里DroneVehicle数据集的annofile用的是什么？方便的话可以分享一份吗 zminghang@std.uestc.edu.cn
还有TSFADet论文好像没有提到到底是用的val还是test做对比（而且他们的annofile好像还有删减？），代码也不公开，test对比表中70.44的数据是得到的？
![屏幕截图 2024-01-10 211849](https://github.com/hexiao-cs/CALNet-Dronevehicle/assets/58153716/2f34da2e-2444-49e5-b46d-675d5fceb88d)

**Comment by hexiao0275** [comment]
I have uploaded annofile and code, only val comparison is used in TSFADet paper. The results of the algorithm on the DroneVehicle test set were given to me by the TSFADet authors.

**Comment by Another-0** [comment]
Thanks! Help me a lot.

**Comment by hexiao0275** [comment]
see [README.md](https://github.com/hexiao-cs/CALNet-Dronevehicle/blob/main/README.md)
