### ISSUE TITLE
OBB vs HBB

### ISSUE THREAD

**Issue by fuqianya** [hexiao-cs/CALNet-Dronevehicle#12]
您好作者，关于OBB和HBB，我有几个问题：

（1）看论文里面（参考下面），这篇论文用的应该是HBB吧？
```
The DroneVehicle annotation box encompasses directional information. To tackle the angle regression problem, we draw inspiration from [46] and transform it into a 180degree classification problem. This approach enables learning of the object orientation by converting the angle of the object into a classification problem within the 0 to 180-degree range.
```
（2）为什么在论文的Table1里面，将Faster R-CNN标注为OBB，Fasater R-CNN不是HBB算法吗？
（3）TSFADet看论文好像也是OBB呀！为啥没有标注为OBB

**Comment by hexiao0275** [comment]
1. CALNet是OBB的，OBB的方向回归参考CSL [46] 论文
2. Table1参考TSFADet的实验，他将Fasater R-CNN改为了OBB
3. 本身是OBB的方法就没有标注了

**Comment by Blissy-32** [comment]
> 您好作者，关于OBB和HBB，我有几个问题：
> 
> （1）看论文里面（参考下面），这篇论文用的应该是HBB吧？
> 
> ```
> The DroneVehicle annotation box encompasses directional information. To tackle the angle regression problem, we draw inspiration from [46] and transform it into a 180degree classification problem. This approach enables learning of the object orientation by converting the angle of the object into a classification problem within the 0 to 180-degree range.
> ```
> 
> （2）为什么在论文的Table1里面，将Faster R-CNN标注为OBB，Fasater R-CNN不是HBB算法吗？ （3）TSFADet看论文好像也是OBB呀！为啥没有标注为OBB

您好! 论文能分享一下么

**Comment by hexiao0275** [comment]
[Translation, scale and rotation: cross-modal alignment meets RGB-infrared vehicle detection](https://link.springer.com/chapter/10.1007/978-3-031-20077-9_30)
