### ISSUE TITLE
大佬能否分享一下pdf版本的论文呢，想学习一下，万分感谢

### ISSUE THREAD

**Issue by clw5180** [hexiao-cs/CALNet-Dronevehicle#15]
ACM无法下载

**Comment by aeeeeeep** [comment]
I can provide this paper
[3581783.3612651.pdf](https://github.com/hexiao0275/CALNet-Dronevehicle/files/15219021/3581783.3612651.pdf)

**Comment by clw5180** [comment]
> I can provide this paper [3581783.3612651.pdf](https://github.com/hexiao0275/CALNet-Dronevehicle/files/15219021/3581783.3612651.pdf)

Thanks a lot! Have you joined the competition and how much score you can get? I think it might be a good baseline.

**Comment by aeeeeeep** [comment]
> > I can provide this paper [3581783.3612651.pdf](https://github.com/hexiao0275/CALNet-Dronevehicle/files/15219021/3581783.3612651.pdf)
> 
> Thanks a lot! Have you joined the competition and how much score you can get? I think it might be a good baseline.

still exploring, current score not good 🥲

**Comment by clw5180** [comment]
> > > I can provide this paper [3581783.3612651.pdf](https://github.com/hexiao0275/CALNet-Dronevehicle/files/15219021/3581783.3612651.pdf)
> > 
> > 
> > Thanks a lot! Have you joined the competition and how much score you can get? I think it might be a good baseline.
> 
> still exploring, current score not good 🥲

I trained 50epoch using 640x512 image (no border), and modify labelTxt's label (-100 and remove truncated boxes), but only got 0.309 score online...

**Comment by clw5180** [comment]
one more thing needs to note:  online categories are: [”car", "truck", "bus", "van", "freight_car"], but here are [”car", "truck", "bus", "freight_car", "van"]
