### ISSUE TITLE
标签是八点的，但是yolo不是四点的吗？请问要怎么改yolo代码才能直接使用您提供的txt标签

### ISSUE THREAD

**Issue by leileilei2000** [hexiao-cs/CALNet-Dronevehicle#2]

**Comment by hexiao0275** [comment]
We have links to download the processed labels in Readme.md, just download the dataset and labels and run it directly.

**Comment by leileilei2000** [comment]
我使用的是您提供的标签，它们确实是txt格式的，但是我想使用yolov5去训练，但是标签是八点的，请问我应该参考哪部分的内容进行修改？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hexiao0275/CALNet-Dronevehicle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月2日(星期五) 下午2:24
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [hexiao0275/CALNet-Dronevehicle] 标签是八点的，但是yolo不是四点的吗？请问要怎么改yolo代码才能直接使用您提供的txt标签 (Issue #2)





 
We have links to download the processed labels in Readme.md, just download the dataset and labels and run it directly.
