### ISSUE TITLE
About the paper

### ISSUE THREAD

**Issue by tungp55** [hexiao-cs/CALNet-Dronevehicle#22]
Great job! I find your method very interesting, and I've been reading up on it. However, the price on Springer is quite high (I'm a student). Could you please send me a draft or a PDF of the paper? Thank you very much.

**Comment by hexiao0275** [comment]
See [3581783.3612651.pdf](https://github.com/hexiao0275/CALNet-Dronevehicle/files/15219021/3581783.3612651.pdf)
