### ISSUE TITLE
File missing？

### ISSUE THREAD

**Issue by Another-0** [hexiao-cs/CALNet-Dronevehicle#3]
yolo.py was modified but not uploaded

**Comment by hexiao0275** [comment]
I have updated the code on github by uploading the yolo.py file. This code is a double-branched directed box code, so there are many changes. The pre-training weights are the pre-training weights that are common to yolov5. I revalidated the code on Github and it is working.

**Comment by hexiao0275** [comment]
Pre-training weights download in Readme.md.
