### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by yaoergogo** [hexiao-cs/CALNet-Dronevehicle#6]
您好，我在运行train.py的时候报了以下的错，您能帮帮我吗
![image](https://github.com/hexiao0275/CALNet-Dronevehicle/assets/118654036/a21b352b-723a-413b-a491-c38368d9af7a)

**Comment by hexiao0275** [comment]
There should be something wrong with your environment, refer to the solution keyword:Pytorch Illegal instruction

**Comment by yaoergogo** [comment]
但是我在cpu上可以运行，我指定在GPU上就会报错

**Comment by yaoergogo** [comment]
> There should be something wrong with your environment, refer to the solution keyword:Pytorch Illegal instruction

![image](https://github.com/hexiao0275/CALNet-Dronevehicle/assets/118654036/de5deb2a-d0af-4f51-84df-95ef0989f188)
您好，这是我的环境，我的cuda版本也是11.3，唯一的区别是我的ubuntu操作系统是20.4的，但这个在cpu上可以运行，在GPU上就会报错，我不知道改怎么解决，你能给点详细的提示吗

**Comment by hexiao0275** [comment]
可能是GPU设置的问题，按理能跑YOLOv5也能跑这个， 你可以尝试：conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
