### ISSUE TITLE
训练和验证使用的GT似乎只使用了RGB模态的labels，这是默认的吗？

### ISSUE THREAD

**Issue by Liuyangfeixiao** [hexiao-cs/CALNet-Dronevehicle#7]
你好，从代码中可以看出，训练得到loss和验证得到mAP所用的都是RGB模态的label，请问这是默认的吗？
也就是说使用红外图像提取特征，但是只使用RGB的label来监督和评估？
<img width="594" alt="Snipaste_2024-04-06_23-15-33" src="https://github.com/hexiao0275/CALNet-Dronevehicle/assets/46079689/474a7f04-ec85-4a5f-8c23-b3c51f23bf2c">

**Comment by leileilei2000** [comment]
请问你在VEDAI上训练了吗？我准备进行这个工作

**Comment by hexiao0275** [comment]
测试在DroneVehicle的红外数据上进行，和之前工作对齐，这个code的RGB和IR的label都是一样的

**Comment by hexiao0275** [comment]
> 请问你在VEDAI上训练了吗？我准备进行这个工作

你可以试试，这个代码效果在遥感数据集上都很有竞争力

**Comment by lalalaland6** [comment]
> 请问你在VEDAI上训练了吗？我准备进行这个工作

请问您在vedai数据集上训练了吗，在vedai数据集上能达到多少的精度呢
